-- ECE496 Language Learning App - Database Schema
-- PostgreSQL Database Schema for Object Recognition & Vocabulary Learning App

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Languages table - supported languages for translations
CREATE TABLE languages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code VARCHAR(10) UNIQUE NOT NULL, -- 'en', 'es', 'zh', 'fr', etc.
    name VARCHAR(100) NOT NULL,
    native_name VARCHAR(100) NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Object categories - categories of objects that can be recognized
CREATE TABLE object_categories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    category_name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    icon_name VARCHAR(50), -- For frontend display
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Words - base vocabulary words
CREATE TABLE words (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    word_text VARCHAR(200) NOT NULL,
    language_code VARCHAR(10) NOT NULL REFERENCES languages(code),
    category_id UUID REFERENCES object_categories(id),
    part_of_speech VARCHAR(50), -- noun, verb, adjective, etc.
    phonetic_transcription VARCHAR(200),
    difficulty_level INTEGER DEFAULT 1, -- 1-5 scale
    is_common BOOLEAN DEFAULT false, -- common vocabulary flag
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(word_text, language_code)
);

-- Translations - translations between languages
CREATE TABLE translations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    source_word_id UUID NOT NULL REFERENCES words(id) ON DELETE CASCADE,
    target_language_code VARCHAR(10) NOT NULL REFERENCES languages(code),
    translated_text VARCHAR(200) NOT NULL,
    confidence_score DECIMAL(3,2) DEFAULT 1.0, -- 0.00-1.00
    is_verified BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(source_word_id, target_language_code)
);

-- Example sentences - generated by GPT
CREATE TABLE example_sentences (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    word_id UUID NOT NULL REFERENCES words(id) ON DELETE CASCADE,
    sentence_text TEXT NOT NULL,
    language_code VARCHAR(10) NOT NULL REFERENCES languages(code),
    translation_language_code VARCHAR(10) REFERENCES languages(code),
    sentence_translation TEXT,
    context_level VARCHAR(20) DEFAULT 'basic', -- basic, intermediate, advanced
    usage_examples JSONB, -- Additional context or examples
    is_verified BOOLEAN DEFAULT false,
    created_by_gpt BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Users - app user accounts
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    native_language_code VARCHAR(10) NOT NULL REFERENCES languages(code),
    target_language_code VARCHAR(10) NOT NULL REFERENCES languages(code),
    profile_image_url VARCHAR(500),
    learning_preferences JSONB, -- preferences, goals, etc.
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User progress - tracks learning progress for each word
CREATE TABLE user_progress (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    word_id UUID NOT NULL REFERENCES words(id) ON DELETE CASCADE,
    recognition_date TIMESTAMP, -- when user first recognized this word
    mastery_level INTEGER DEFAULT 0, -- 0-5 scale, 0 = not learned, 5 = mastered
    review_count INTEGER DEFAULT 0,
    last_reviewed_at TIMESTAMP,
    next_review_date TIMESTAMP,
    is_learned BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, word_id)
);

-- Learning sessions - records of learning sessions
CREATE TABLE learning_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_date DATE NOT NULL,
    words_learned INTEGER DEFAULT 0,
    words_reviewed INTEGER DEFAULT 0,
    session_duration INTEGER, -- in seconds
    session_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Recognition events - tracks when objects are recognized
CREATE TABLE recognition_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    word_id UUID NOT NULL REFERENCES words(id),
    session_id UUID REFERENCES learning_sessions(id),
    recognition_confidence DECIMAL(3,2), -- confidence of AI recognition
    user_feedback BOOLEAN, -- user confirmed or corrected the recognition
    image_url VARCHAR(500), -- optional: store recognition image
    recognition_metadata JSONB, -- additional recognition data
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance optimization
CREATE INDEX idx_words_language ON words(language_code);
CREATE INDEX idx_words_category ON words(category_id);
CREATE INDEX idx_translations_source ON translations(source_word_id);
CREATE INDEX idx_translations_target ON translations(target_language_code);
CREATE INDEX idx_example_sentences_word ON example_sentences(word_id);
CREATE INDEX idx_user_progress_user ON user_progress(user_id);
CREATE INDEX idx_user_progress_word ON user_progress(word_id);
CREATE INDEX idx_recognition_events_user ON recognition_events(user_id);
CREATE INDEX idx_recognition_events_word ON recognition_events(word_id);
CREATE INDEX idx_learning_sessions_user_date ON learning_sessions(user_id, session_date);

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply trigger to relevant tables
CREATE TRIGGER update_words_updated_at BEFORE UPDATE ON words
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_translations_updated_at BEFORE UPDATE ON translations
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_progress_updated_at BEFORE UPDATE ON user_progress
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();